title:            Adler Vermillion, LLP
description:      Lawyers for Technology and Design Innovators in New York City.
logo:             site-logo.png
disqus_shortname: adlervermillion
search:           false
# Change url to your domain. Leave localhost server or blank when working locally.
url:               http://adlervermillion.com              

# Owner/author information
owner:
  name:           Eric Adler
  avatar:         EricAvatar.jpg
  email:          you@email.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        teachingaway  
  facebook:       
  github:         
  stackexchange:  
  linkedin:       
  instagram:      
  flickr:         
  tumblr:         
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    

#attempting to add multiple blog authors - 6/5/2014
authors:
  adler:
    name:           Eric Adler
    avatar:         EricAvatar.jpg
    email:          eric@adlervermillion
    aboutpage:      ericadler
    twitter:        teachingaway
    linkedin:       'in/ericladler'
  vermillion:
    name:           Zeke Vermillion
    avatar:         ZekeAvatar.jpg
    aboutpage:      zekevermillion
    email:          zeke@adlervermillion
    twitter:        zmillion 
    linkedin:       
  derevyanny: 
    name:           Jerry Derevyanny
    avatar:         JerryAvatar.jpg
    aboutpage:      jerryderevyanny
    email:          jerry@adlervermillion
    twitter:        
    linkedin:       pub/gerald-derevyanny/8/969/a70
  skocilich: 
    name:           Joe Skocilich
    avatar:         JoeAvatar.jpg
    aboutpage:      #
    email:          #
    twitter:        joeskocilich 
    linkedin:       #


# Analytics and webmaster tools stuff goes here
google_analytics:   UA-27681557-1
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# Links to include in top navigation
# For external links add external: true
links:
  - title: Blog
    url: /articles/
  - title: Attorneys
    url: /attorneys/
  - title: Office Hours
    url: /office-hours/

# Links to include in footer navigation
footerlinks:
  - title: Business law
    url: /business-law/
  - title: Patents
    url: /patent-services/
  - title: Trademarks
    url: /trademark-services/
  - title: Litigation
    url: /litigation/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
highlighter: pygments
markdown:    kramdown
kramdown: 

  
# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/


kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true
  
  parse_block_html: false
  parse_span_html: false
  remove_block_html_tags: true
  remove_span_html_tags: false
  
  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess", "_pages", "mpep", "pages"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", 'pixelmator_files', 'drafts']
